# Site settings
title: SDL Raycasting Game Engine
description: A simple 2D raycasting-based game engine built using SDL2 in C
baseurl: "/SDL_Project " # The subpath of your site, e.g. /SDL_Project
url: "https://shiftyshadows.github.io/SDL_Project" # Your GitHub Pages URL

# Author details
author: shiftyshadows
email: purple.quasar@proton.me

# Repository settings
repository: shiftyshadows/SDL_Project # Update with your GitHub repo
use_full_site_title: true

# GitHub Pages theme
#theme: minima

# Social links (optional)
social_links:
  - name: GitHub
    url: https://github.com/shiftyshadows/raycasting-game
  - name: Twitter
    url: https://x.com/shifty_shadows


# Exclude certain files from Jekyll processing (if applicable)
exclude:
  - README.md
  - LICENSE
  - _config.yml

# Plugins (optional)
plugins:
  - jekyll-seo-tag # SEO plugin for better site indexing
  - jekyll-sitemap # Auto-generates a sitemap.xml
  - jekyll-remote-theme
# Markdown settings
markdown: kramdown
kramdown:
  input: GFM

# Include custom static assets
include:
  - _assets/

# Additional customizations (optional)
permalink: pretty
paginate: 10

remote_theme: pages-themes/architect@v0.2.0
