# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.
#
# If you need help with YAML syntax, here are some quick references for you:
# https://learn-the-web.algonquindesign.ca/topics/markdown-yaml-cheat-sheet/#yaml
# https://learnxinyminutes.com/docs/yaml/
#
# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.


# Site settings
title: SDL Raycasting Game Engine
email: purple.quasar@proton.me
description: A simple 2D raycasting-based game engine built using SDL2 in C
baseurl: "/SDL_Project" # The subpath of your site, e.g. /raycasting-game
url: "https://shiftyshadows.github.io/SDL_Project" # Your GitHub Pages URL


twitter_username: shifty_shadows
github_username:  shiftyshadows

# Author details
author: shiftyshadows
email: purple.quasar@proton.me

# Repository settings
repository: shifty_shadows/SDL_Project # Update with your GitHub repo
use_full_site_title: true

# Build settings
#theme: minima
theme: jekyll-theme-architect
remote_theme: pages-themes/architect@v0.2.0
plugins:
  - jekyll-feed
  - jekyll-remote-theme
# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
#
# exclude:
#   - .sass-cache/
#   - .jekyll-cache/
#   - gemfiles/
#   - Gemfile
#   - Gemfile.lock
#   - node_modules/
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
